---

- hosts: dc
  become: yes 
  vars:
    doc_root: "/var/www/html"

  tasks:
  - name: Install Apache Packages
    apt: name=apache2 state=present

  - name: Start Apache Service 
    service: name=apache2 state=started

  - name: Deploy Custom Info file
    copy: src=templates/info.html dest={{doc_root}}/info.html

  - name: Deploy Jenkins Info file
    copy: src=templates/jenkins.html dest={{doc_root}}/jenkins.html

  - name: Start Java Service 
    apt: name=openjdk-8-jdk state=present

  
  - name: Deploy Custom Info file
    copy: src=templates/atmosphere-v1.jar dest={{doc_root}}/atmosphere-v1.jar

  - name: Start Atmosphere Application. 
    shell: nohup /usr/bin/java -jar {{doc_root}}/atmosphere-v1.jar & > nohup.out
